workflows:
  ios-development-build:
    name: iOS Build (Paid Apple Developer Account)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic_apple_id
    environment:
      xcode: latest
      vars:
        SUPABASE_STAGING_URL: https://dqqyhmydodjpqboykzow.supabase.co
        SUPABASE_STAGING_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcXlobXlkb2RqcHFib3lrem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTQ1MzUsImV4cCI6MjA3OTY3MDUzNX0.I6rNpnUIzk05VM-3MCTTTFbIEm7VRttYXFpbiITn2gg
        SUPABASE_PRODUCTION_URL: https://bapwklwxmwhpucutyras.supabase.co
        SUPABASE_PRODUCTION_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcHdrbHd4bXdocHVjdXR5cmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMDA2MjUsImV4cCI6MjA3OTY3NjYyNX0.1logTpQ9UnMDzYsZytjL6HAWFpknuMOyqGu0TyWj6eA
        FIREBASE_API_KEY: AIzaSyBuS1snryQ_DWxhcEUtj0Lu_HDrdIvASDY
        FIREBASE_AUTH_DOMAIN: silni-31811.firebaseapp.com
        FIREBASE_PROJECT_ID: silni-31811
        FIREBASE_STORAGE_BUCKET: silni-31811.firebasestorage.app
        FIREBASE_MESSAGING_SENDER_ID: "104991741546"
        FIREBASE_APP_ID: 1:104991741546:web:baa2792c28877379412f13
        FIREBASE_MEASUREMENT_ID: G-JMW4oM9PXM
        CLOUDINARY_CLOUD_NAME: dli79vqgg
        CLOUDINARY_UPLOAD_PRESET: silni_unsigned
        APP_ENV: staging
      flutter: stable
      cocoapods: default
    scripts:
      - name: Set up environment variables
        script: |
          cat > .env << 'EOF'
          FIREBASE_API_KEY=AIzaSyBuS1snryQ_DWxhcEUtj0Lu_HDrdIvASDY
          FIREBASE_AUTH_DOMAIN=silni-31811.firebaseapp.com
          FIREBASE_PROJECT_ID=silni-31811
          FIREBASE_STORAGE_BUCKET=silni-31811.firebasestorage.app
          FIREBASE_MESSAGING_SENDER_ID=104991741546
          FIREBASE_APP_ID=1:104991741546:web:baa2792c28877379412f13
          FIREBASE_MEASUREMENT_ID=G-JMW4oM9PXM
          SUPABASE_STAGING_URL=https://dqqyhmydodjpqboykzow.supabase.co
          SUPABASE_STAGING_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcXlobXlkb2RqcHFib3lrem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTQ1MzUsImV4cCI6MjA3OTY3MDUzNX0.I6rNpnUIzk05VM-3MCTTTFbIEm7VRttYXFpbiITn2gg
          SUPABASE_PRODUCTION_URL=https://bapwklwxmwhpucutyras.supabase.co
          SUPABASE_PRODUCTION_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcHdrbHd4bXdocHVjdXR5cmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMDA2MjUsImV4cCI6MjA3OTY3NjYyNX0.1logTpQ9UnMDzYsZytjL6HAWFpknuMOyqGu0TyWj6eA
          CLOUDINARY_CLOUD_NAME=dli79vqgg
          CLOUDINARY_API_KEY=your_cloudinary_api_key
          CLOUDINARY_API_SECRET=your_cloudinary_api_secret
          CLOUDINARY_UPLOAD_PRESET=silni_unsigned
          APP_ENV=staging
          EOF
          echo "âœ… Environment file created"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Setup code signing
        script: |
          # Register device and create provisioning profile
          set -e
          keychain initialize

          echo "ðŸ” Creating new development certificate..."
          app-store-connect certificates create \
            --type IOS_DEVELOPMENT \
            --save || echo "Certificate creation skipped"

          echo "ðŸ” Fetching signing files..."
          app-store-connect fetch-signing-files com.silni.app \
            --type IOS_APP_DEVELOPMENT \
            --create \
            --verbose

          echo "âœ… Applying profiles to Xcode project..."
          xcode-project use-profiles
      - name: Flutter analyze
        script: |
          flutter analyze || true
      - name: Build iOS app
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  android-build:
    name: Android Build (Easy Multi-User Testing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        SUPABASE_STAGING_URL: https://dqqyhmydodjpqboykzow.supabase.co
        SUPABASE_STAGING_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcXlobXlkb2RqcHFib3lrem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTQ1MzUsImV4cCI6MjA3OTY3MDUzNX0.I6rNpnUIzk05VM-3MCTTTFbIEm7VRttYXFpbiITn2gg
        SUPABASE_PRODUCTION_URL: https://bapwklwxmwhpucutyras.supabase.co
        SUPABASE_PRODUCTION_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcHdrbHd4bXdocHVjdXR5cmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMDA2MjUsImV4cCI6MjA3OTY3NjYyNX0.1logTpQ9UnMDzYsZytjL6HAWFpknuMOyqGu0TyWj6eA
        FIREBASE_API_KEY: AIzaSyBuS1snryQ_DWxhcEUtj0Lu_HDrdIvASDY
        FIREBASE_AUTH_DOMAIN: silni-31811.firebaseapp.com
        FIREBASE_PROJECT_ID: silni-31811
        FIREBASE_STORAGE_BUCKET: silni-31811.firebasestorage.app
        FIREBASE_MESSAGING_SENDER_ID: "104991741546"
        FIREBASE_APP_ID: 1:104991741546:web:baa2792c28877379412f13
        FIREBASE_MEASUREMENT_ID: G-JMW4oM9PXM
        CLOUDINARY_CLOUD_NAME: dli79vqgg
        CLOUDINARY_UPLOAD_PRESET: silni_unsigned
        APP_ENV: production
      flutter: stable
      java: 17
    scripts:
      - name: Set up environment variables
        script: |
          cat > .env << 'EOF'
          FIREBASE_API_KEY=AIzaSyBuS1snryQ_DWxhcEUtj0Lu_HDrdIvASDY
          FIREBASE_AUTH_DOMAIN=silni-31811.firebaseapp.com
          FIREBASE_PROJECT_ID=silni-31811
          FIREBASE_STORAGE_BUCKET=silni-31811.firebasestorage.app
          FIREBASE_MESSAGING_SENDER_ID=104991741546
          FIREBASE_APP_ID=1:104991741546:web:baa2792c28877379412f13
          FIREBASE_MEASUREMENT_ID=G-JMW4oM9PXM
          SUPABASE_STAGING_URL=https://dqqyhmydodjpqboykzow.supabase.co
          SUPABASE_STAGING_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcXlobXlkb2RqcHFib3lrem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTQ1MzUsImV4cCI6MjA3OTY3MDUzNX0.I6rNpnUIzk05VM-3MCTTTFbIEm7VRttYXFpbiITn2gg
          SUPABASE_PRODUCTION_URL=https://bapwklwxmwhpucutyras.supabase.co
          SUPABASE_PRODUCTION_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcHdrbHd4bXdocHVjdXR5cmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMDA2MjUsImV4cCI6MjA3OTY3NjYyNX0.1logTpQ9UnMDzYsZytjL6HAWFpknuMOyqGu0TyWj6eA
          CLOUDINARY_CLOUD_NAME=dli79vqgg
          CLOUDINARY_API_KEY=your_cloudinary_api_key
          CLOUDINARY_API_SECRET=your_cloudinary_api_secret
          CLOUDINARY_UPLOAD_PRESET=silni_unsigned
          APP_ENV=production
          EOF
          echo "âœ… Environment file created"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --flavor production
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true
