import '../../../core/config/supabase_config.dart';
import '../models/family_group_model.dart';

/// Static service for family group CRUD operations.
///
/// Follows the project convention of private constructor + static methods.
/// Wraps Supabase calls for creating, joining, and managing family groups.
class FamilyGroupService {
  FamilyGroupService._();

  // ---------------------------------------------------------------------------
  // Group management
  // ---------------------------------------------------------------------------

  /// Create a new family group and add the creator as admin.
  ///
  /// Returns the newly created [FamilyGroup] with its generated invite code.
  static Future<FamilyGroup> createGroup({
    required String name,
    required String userId,
  }) async {
    final client = SupabaseConfig.client;

    // Insert group — invite_code is auto-generated by the DB default
    final groupData = await client
        .from('family_groups')
        .insert({
          'name': name,
          'created_by': userId,
        })
        .select()
        .single();

    final group = FamilyGroup.fromJson(groupData);

    // Add creator as admin member
    await client.from('family_group_members').insert({
      'group_id': group.id,
      'user_id': userId,
      'role': 'admin',
    });

    return group;
  }

  /// Generate a shareable invite deep link for a group.
  static String generateInviteLink(String inviteCode) {
    return 'https://silni.app/join/$inviteCode';
  }

  /// Join a group by invite code.
  ///
  /// Looks up the group by [inviteCode] via secure RPC, then adds [userId]
  /// as a member. Skips insertion if already a member (preserves existing role).
  /// Throws if the invite code is invalid.
  static Future<FamilyGroup> joinGroup({
    required String inviteCode,
    required String userId,
    String? relativeIdInTree,
  }) async {
    final client = SupabaseConfig.client;

    // Look up group by invite code via SECURITY DEFINER function
    final groupData = await client
        .rpc('lookup_group_by_invite_code', params: {'code': inviteCode})
        .single();

    final group = FamilyGroup.fromJson(groupData);

    // Check if already a member (to avoid overwriting role)
    final existing = await client
        .from('family_group_members')
        .select('id')
        .eq('group_id', group.id)
        .eq('user_id', userId)
        .maybeSingle();

    if (existing == null) {
      // Only insert if not already a member
      await client.from('family_group_members').insert({
        'group_id': group.id,
        'user_id': userId,
        'role': 'member',
        if (relativeIdInTree != null) 'relative_id_in_tree': relativeIdInTree,
      });

      // Fire-and-forget join notification to existing members
      _sendJoinNotification(
        groupId: group.id,
        newUserId: userId,
        familyName: group.name,
      );
    }

    return group;
  }

  /// Fire-and-forget join notification to group members.
  static Future<void> _sendJoinNotification({
    required String groupId,
    required String newUserId,
    required String familyName,
  }) async {
    try {
      final client = SupabaseConfig.client;

      // Get all OTHER members to notify
      final members = await client
          .from('family_group_members')
          .select('user_id')
          .eq('group_id', groupId)
          .neq('user_id', newUserId);

      // Fetch the join notification template from admin panel
      final template = await client
          .from('admin_notification_templates')
          .select()
          .eq('template_key', 'family_join_1')
          .eq('is_active', true)
          .maybeSingle();

      if (template == null) return;

      final body = (template['body_ar'] as String)
          .replaceAll('{{member_name}}', 'عضو جديد')
          .replaceAll('{{family_name}}', familyName);
      final title = template['title_ar'] as String;

      // Send to each member via the existing push function
      for (final member in members) {
        await client.functions.invoke('send-push-notification', body: {
          'userId': member['user_id'],
          'notificationType': 'system',
          'title': title,
          'body': body,
          'data': {'type': 'family_join', 'group_id': groupId},
        });
      }
    } catch (_) {
      // Fire-and-forget — don't block join flow on notification failure
    }
  }

  // ---------------------------------------------------------------------------
  // Query methods
  // ---------------------------------------------------------------------------

  /// Get all groups the user belongs to.
  ///
  /// Queries through the members table to ensure only the user's groups are
  /// returned, regardless of RLS configuration.
  static Future<List<FamilyGroup>> getUserGroups(String userId) async {
    final client = SupabaseConfig.client;
    final data = await client
        .from('family_group_members')
        .select('family_groups(*)')
        .eq('user_id', userId)
        .order('joined_at', ascending: false);

    return data
        .where((row) => row['family_groups'] != null)
        .map((row) =>
            FamilyGroup.fromJson(row['family_groups'] as Map<String, dynamic>))
        .toList();
  }

  /// Get members of a specific group.
  ///
  /// Returns members ordered by join date (oldest first).
  static Future<List<FamilyGroupMember>> getGroupMembers(
    String groupId,
  ) async {
    final client = SupabaseConfig.client;
    final data = await client
        .from('family_group_members')
        .select()
        .eq('group_id', groupId)
        .order('joined_at');
    return data.map((json) => FamilyGroupMember.fromJson(json)).toList();
  }

  /// Look up a group by its invite code without joining.
  ///
  /// Uses a SECURITY DEFINER function to bypass RLS for invite code lookup.
  /// Returns `null` if no group with the given code exists.
  static Future<FamilyGroup?> lookupGroupByInviteCode(
    String inviteCode,
  ) async {
    final client = SupabaseConfig.client;
    final data = await client
        .rpc('lookup_group_by_invite_code', params: {'code': inviteCode});

    final results = data as List<dynamic>;
    if (results.isEmpty) return null;
    return FamilyGroup.fromJson(results.first as Map<String, dynamic>);
  }

  /// Check if a user is already a member of a group.
  static Future<bool> isMember({
    required String groupId,
    required String userId,
  }) async {
    final client = SupabaseConfig.client;
    final data = await client
        .from('family_group_members')
        .select('id')
        .eq('group_id', groupId)
        .eq('user_id', userId)
        .maybeSingle();

    return data != null;
  }

  // ---------------------------------------------------------------------------
  // Member management
  // ---------------------------------------------------------------------------

  /// Leave a group.
  ///
  /// Removes the user from the group's member list.
  static Future<void> leaveGroup({
    required String groupId,
    required String userId,
  }) async {
    await SupabaseConfig.client
        .from('family_group_members')
        .delete()
        .eq('group_id', groupId)
        .eq('user_id', userId);
  }

  /// Delete a group (admin only — enforced by RLS).
  static Future<void> deleteGroup(String groupId) async {
    await SupabaseConfig.client
        .from('family_groups')
        .delete()
        .eq('id', groupId);
  }
}
