-- Seed admin_themes table with the 6 hardcoded themes from app_themes.dart
-- This allows themes to be managed from the admin panel while maintaining backward compatibility

-- Ensure the table exists (should already exist from admin_panel_phase1.sql)
CREATE TABLE IF NOT EXISTS admin_themes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  theme_key TEXT NOT NULL UNIQUE,
  display_name_ar TEXT NOT NULL,
  display_name_en TEXT,
  is_dark BOOLEAN DEFAULT FALSE,
  colors JSONB NOT NULL DEFAULT '{}',
  gradients JSONB NOT NULL DEFAULT '{}',
  shadows JSONB NOT NULL DEFAULT '{}',
  is_premium BOOLEAN DEFAULT FALSE,
  is_default BOOLEAN DEFAULT FALSE,
  preview_image_url TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the 6 hardcoded themes
INSERT INTO admin_themes (
  theme_key,
  display_name_ar,
  display_name_en,
  is_dark,
  colors,
  gradients,
  is_premium,
  is_default,
  sort_order
) VALUES
-- 1. Default Green (صِلني) - FREE, DEFAULT
(
  'default',
  'صِلني',
  'Silni Green',
  FALSE,
  '{
    "primary": "#2E7D32",
    "primary_light": "#60AD5E",
    "primary_dark": "#005005",
    "secondary": "#FFD700",
    "accent": "#FF6F00",
    "background_1": "#1B5E20",
    "background_2": "#2E7D32",
    "background_3": "#388E3C",
    "on_primary": "#FFFFFF",
    "on_secondary": "#1B5E20",
    "surface": "#1B5E20",
    "on_surface": "#FFFFFF",
    "surface_variant": "#2E7D32",
    "on_surface_variant": "#E8F5E9",
    "glass_background": "#26FFFFFF",
    "glass_border": "#33FFFFFF",
    "glass_highlight": "#4DFFFFFF",
    "text_primary": "#FFFFFF",
    "text_secondary": "#B3FFFFFF",
    "text_hint": "#80FFFFFF",
    "text_on_gradient": "#FFFFFF",
    "shimmer_base": "#2E7D32",
    "shimmer_highlight": "#81C784",
    "card_background": "#26FFFFFF",
    "card_border": "#33FFFFFF",
    "divider": "#33FFFFFF",
    "disabled": "#80FFFFFF"
  }',
  '{
    "primary": {"colors": ["#2E7D32", "#60AD5E", "#81C784"]},
    "background": {"colors": ["#1B5E20", "#2E7D32", "#388E3C"]},
    "golden": {"colors": ["#FFD700", "#FFA000", "#FF6F00"]},
    "streak_fire": {"colors": ["#FF6F00", "#FF8F00", "#FFA726"]}
  }',
  FALSE,
  TRUE,
  0
),
-- 2. Lavender Purple (خزامى) - PREMIUM
(
  'lavender',
  'خزامى',
  'Lavender Purple',
  FALSE,
  '{
    "primary": "#7B1FA2",
    "primary_light": "#BA68C8",
    "primary_dark": "#4A0072",
    "secondary": "#FFD700",
    "accent": "#E040FB",
    "background_1": "#4A148C",
    "background_2": "#6A1B9A",
    "background_3": "#7B1FA2",
    "on_primary": "#FFFFFF",
    "on_secondary": "#4A148C",
    "surface": "#4A148C",
    "on_surface": "#FFFFFF",
    "surface_variant": "#6A1B9A",
    "on_surface_variant": "#F3E5F5",
    "glass_background": "#26FFFFFF",
    "glass_border": "#33FFFFFF",
    "glass_highlight": "#4DFFFFFF",
    "text_primary": "#FFFFFF",
    "text_secondary": "#B3FFFFFF",
    "text_hint": "#80FFFFFF",
    "text_on_gradient": "#FFFFFF",
    "shimmer_base": "#7B1FA2",
    "shimmer_highlight": "#BA68C8",
    "card_background": "#26FFFFFF",
    "card_border": "#33FFFFFF",
    "divider": "#33FFFFFF",
    "disabled": "#80FFFFFF"
  }',
  '{
    "primary": {"colors": ["#7B1FA2", "#9C27B0", "#BA68C8"]},
    "background": {"colors": ["#4A148C", "#6A1B9A", "#7B1FA2"]},
    "golden": {"colors": ["#FFD700", "#FFA000", "#FF6F00"]},
    "streak_fire": {"colors": ["#E040FB", "#CE93D8", "#BA68C8"]}
  }',
  TRUE,
  FALSE,
  1
),
-- 3. Royal Blue (الأزرق الملكي) - PREMIUM
(
  'royal',
  'الأزرق الملكي',
  'Royal Blue',
  FALSE,
  '{
    "primary": "#1565C0",
    "primary_light": "#5E92F3",
    "primary_dark": "#003C8F",
    "secondary": "#FFD700",
    "accent": "#00B0FF",
    "background_1": "#0D47A1",
    "background_2": "#1565C0",
    "background_3": "#1976D2",
    "on_primary": "#FFFFFF",
    "on_secondary": "#0D47A1",
    "surface": "#0D47A1",
    "on_surface": "#FFFFFF",
    "surface_variant": "#1565C0",
    "on_surface_variant": "#E3F2FD",
    "glass_background": "#26FFFFFF",
    "glass_border": "#33FFFFFF",
    "glass_highlight": "#4DFFFFFF",
    "text_primary": "#FFFFFF",
    "text_secondary": "#B3FFFFFF",
    "text_hint": "#80FFFFFF",
    "text_on_gradient": "#FFFFFF",
    "shimmer_base": "#1565C0",
    "shimmer_highlight": "#42A5F5",
    "card_background": "#26FFFFFF",
    "card_border": "#33FFFFFF",
    "divider": "#33FFFFFF",
    "disabled": "#80FFFFFF"
  }',
  '{
    "primary": {"colors": ["#1565C0", "#1976D2", "#42A5F5"]},
    "background": {"colors": ["#0D47A1", "#1565C0", "#1976D2"]},
    "golden": {"colors": ["#FFD700", "#FFA000", "#FF6F00"]},
    "streak_fire": {"colors": ["#00B0FF", "#40C4FF", "#80D8FF"]}
  }',
  TRUE,
  FALSE,
  2
),
-- 4. Sunset Orange (غروب الشمس) - PREMIUM
(
  'sunset',
  'غروب الشمس',
  'Sunset Orange',
  FALSE,
  '{
    "primary": "#E65100",
    "primary_light": "#FF8A50",
    "primary_dark": "#AC1900",
    "secondary": "#FFD700",
    "accent": "#FF6F00",
    "background_1": "#BF360C",
    "background_2": "#D84315",
    "background_3": "#E64A19",
    "on_primary": "#FFFFFF",
    "on_secondary": "#BF360C",
    "surface": "#BF360C",
    "on_surface": "#FFFFFF",
    "surface_variant": "#D84315",
    "on_surface_variant": "#FBE9E7",
    "glass_background": "#26FFFFFF",
    "glass_border": "#33FFFFFF",
    "glass_highlight": "#4DFFFFFF",
    "text_primary": "#FFFFFF",
    "text_secondary": "#B3FFFFFF",
    "text_hint": "#80FFFFFF",
    "text_on_gradient": "#FFFFFF",
    "shimmer_base": "#E65100",
    "shimmer_highlight": "#FF9800",
    "card_background": "#26FFFFFF",
    "card_border": "#33FFFFFF",
    "divider": "#33FFFFFF",
    "disabled": "#80FFFFFF"
  }',
  '{
    "primary": {"colors": ["#E65100", "#FF6F00", "#FF9800"]},
    "background": {"colors": ["#BF360C", "#D84315", "#E64A19"]},
    "golden": {"colors": ["#FFD700", "#FFA000", "#FF6F00"]},
    "streak_fire": {"colors": ["#FF6F00", "#FF8F00", "#FFA726"]}
  }',
  TRUE,
  FALSE,
  3
),
-- 5. Rose Gold (ذهبي وردي) - PREMIUM
(
  'rose',
  'ذهبي وردي',
  'Rose Gold',
  FALSE,
  '{
    "primary": "#C2185B",
    "primary_light": "#F06292",
    "primary_dark": "#880E4F",
    "secondary": "#FFD700",
    "accent": "#FF4081",
    "background_1": "#880E4F",
    "background_2": "#AD1457",
    "background_3": "#C2185B",
    "on_primary": "#FFFFFF",
    "on_secondary": "#880E4F",
    "surface": "#880E4F",
    "on_surface": "#FFFFFF",
    "surface_variant": "#AD1457",
    "on_surface_variant": "#FCE4EC",
    "glass_background": "#26FFFFFF",
    "glass_border": "#33FFFFFF",
    "glass_highlight": "#4DFFFFFF",
    "text_primary": "#FFFFFF",
    "text_secondary": "#B3FFFFFF",
    "text_hint": "#80FFFFFF",
    "text_on_gradient": "#FFFFFF",
    "shimmer_base": "#C2185B",
    "shimmer_highlight": "#F06292",
    "card_background": "#26FFFFFF",
    "card_border": "#33FFFFFF",
    "divider": "#33FFFFFF",
    "disabled": "#80FFFFFF"
  }',
  '{
    "primary": {"colors": ["#C2185B", "#E91E63", "#F06292"]},
    "background": {"colors": ["#880E4F", "#AD1457", "#C2185B"]},
    "golden": {"colors": ["#FFD700", "#FFA000", "#FF6F00"]},
    "streak_fire": {"colors": ["#FF4081", "#FF80AB", "#F48FB1"]}
  }',
  TRUE,
  FALSE,
  4
),
-- 6. Midnight Dark (ليل) - PREMIUM
(
  'midnight',
  'ليل',
  'Midnight Dark',
  TRUE,
  '{
    "primary": "#1A237E",
    "primary_light": "#534BAE",
    "primary_dark": "#000051",
    "secondary": "#FFD700",
    "accent": "#536DFE",
    "background_1": "#0A0E27",
    "background_2": "#1A237E",
    "background_3": "#283593",
    "on_primary": "#FFFFFF",
    "on_secondary": "#0A0E27",
    "surface": "#0A0E27",
    "on_surface": "#FFFFFF",
    "surface_variant": "#1A237E",
    "on_surface_variant": "#E8EAF6",
    "glass_background": "#26FFFFFF",
    "glass_border": "#33FFFFFF",
    "glass_highlight": "#4DFFFFFF",
    "text_primary": "#FFFFFF",
    "text_secondary": "#B3FFFFFF",
    "text_hint": "#80FFFFFF",
    "text_on_gradient": "#FFFFFF",
    "shimmer_base": "#1A237E",
    "shimmer_highlight": "#3949AB",
    "card_background": "#26FFFFFF",
    "card_border": "#33FFFFFF",
    "divider": "#33FFFFFF",
    "disabled": "#80FFFFFF"
  }',
  '{
    "primary": {"colors": ["#1A237E", "#283593", "#3949AB"]},
    "background": {"colors": ["#0A0E27", "#1A237E", "#283593"]},
    "golden": {"colors": ["#FFD700", "#FFA000", "#FF6F00"]},
    "streak_fire": {"colors": ["#536DFE", "#7C4DFF", "#B388FF"]}
  }',
  TRUE,
  FALSE,
  5
)
ON CONFLICT (theme_key) DO UPDATE SET
  display_name_ar = EXCLUDED.display_name_ar,
  display_name_en = EXCLUDED.display_name_en,
  is_dark = EXCLUDED.is_dark,
  colors = EXCLUDED.colors,
  gradients = EXCLUDED.gradients,
  is_premium = EXCLUDED.is_premium,
  is_default = EXCLUDED.is_default,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();

-- Note: RLS policies for admin_themes are defined in admin_panel_phase1.sql
-- "Admins can manage themes" - FOR ALL USING (is_admin())
-- "Users can read active themes" - FOR SELECT USING (is_active = true)
