import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_contacts/flutter_contacts.dart';
import 'package:go_router/go_router.dart';
import 'package:confetti/confetti.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_spacing.dart';
import '../../../core/constants/app_typography.dart';
import '../../../core/theme/theme_provider.dart';
import '../../../core/theme/app_themes.dart';
import '../../../core/router/app_routes.dart';
import '../../../shared/widgets/gradient_background.dart';
import '../../../shared/widgets/glass_card.dart';
import '../../../shared/widgets/gradient_button.dart';
import '../../../shared/models/relative_model.dart';
import '../../../shared/services/relatives_service.dart';
import '../../auth/providers/auth_provider.dart';

class ContactImportScreen extends ConsumerStatefulWidget {
  const ContactImportScreen({super.key});

  @override
  ConsumerState<ContactImportScreen> createState() => _ContactImportScreenState();
}

class _ContactImportScreenState extends ConsumerState<ContactImportScreen> {
  final RelativesService _relativesService = RelativesService();
  final TextEditingController _searchController = TextEditingController();
  final ConfettiController _confettiController = ConfettiController(
    duration: const Duration(seconds: 3),
  );

  List<Contact> _allContacts = [];
  List<Contact> _filteredContacts = [];
  Set<String> _selectedContactIds = {};
  bool _isLoading = true;
  bool _permissionDenied = false;
  bool _isImporting = false;

  @override
  void initState() {
    super.initState();
    _loadContacts();
  }

  @override
  void dispose() {
    _searchController.dispose();
    _confettiController.dispose();
    super.dispose();
  }

  Future<void> _loadContacts() async {
    try {
      // Request permission
      if (await FlutterContacts.requestPermission()) {
        final contacts = await FlutterContacts.getContacts(
          withProperties: true,
          withPhoto: false,
        );

        // Filter contacts that have at least a name
        final validContacts = contacts.where((c) => c.displayName.isNotEmpty).toList();

        // Sort alphabetically
        validContacts.sort((a, b) => a.displayName.compareTo(b.displayName));

        setState(() {
          _allContacts = validContacts;
          _filteredContacts = validContacts;
          _isLoading = false;
        });
      } else {
        setState(() {
          _permissionDenied = true;
          _isLoading = false;
        });
      }
    } catch (e) {
      setState(() {
        _isLoading = false;
      });
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('خطأ في تحميل جهات الاتصال: $e')),
        );
      }
    }
  }

  void _filterContacts(String query) {
    setState(() {
      if (query.isEmpty) {
        _filteredContacts = _allContacts;
      } else {
        _filteredContacts = _allContacts
            .where((contact) =>
                contact.displayName.toLowerCase().contains(query.toLowerCase()))
            .toList();
      }
    });
  }

  void _toggleContact(String contactId) {
    HapticFeedback.selectionClick();
    setState(() {
      if (_selectedContactIds.contains(contactId)) {
        _selectedContactIds.remove(contactId);
      } else {
        _selectedContactIds.add(contactId);
      }
    });
  }

  void _selectAll() {
    HapticFeedback.mediumImpact();
    setState(() {
      if (_selectedContactIds.length == _filteredContacts.length) {
        _selectedContactIds.clear();
      } else {
        _selectedContactIds = _filteredContacts.map((c) => c.id).toSet();
      }
    });
  }

  Future<void> _importSelected() async {
    if (_selectedContactIds.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('الرجاء اختيار جهة اتصال واحدة على الأقل')),
      );
      return;
    }

    setState(() => _isImporting = true);

    try {
      final user = ref.read(currentUserProvider);
      if (user == null) {
        throw Exception('User not authenticated');
      }

      int successCount = 0;
      int errorCount = 0;

      for (final contactId in _selectedContactIds) {
        try {
          final contact = _allContacts.firstWhere((c) => c.id == contactId);

          // Get first phone number if available
          final phoneNumber = contact.phones.isNotEmpty ? contact.phones.first.number : null;

          // Create relative from contact
          final relative = Relative(
            id: '', // Will be generated by Firestore
            userId: user.uid,
            fullName: contact.displayName,
            relationshipType: RelationshipType.other, // Default to "other"
            phoneNumber: phoneNumber,
            createdAt: DateTime.now(),
          );

          await _relativesService.createRelative(relative);
          successCount++;
        } catch (e) {
          errorCount++;
        }
      }

      setState(() => _isImporting = false);

      if (successCount > 0) {
        _confettiController.play();
        HapticFeedback.heavyImpact();

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('تم استيراد $successCount جهة اتصال بنجاح! 🎉'),
              backgroundColor: AppColors.islamicGreenPrimary,
            ),
          );
        }

        // Navigate back to home after a short delay
        await Future.delayed(const Duration(seconds: 2));
        if (mounted) {
          context.go(AppRoutes.home);
        }
      }

      if (errorCount > 0 && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('فشل استيراد $errorCount جهة اتصال'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } catch (e) {
      setState(() => _isImporting = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('خطأ في الاستيراد: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final themeColors = ref.watch(themeColorsProvider);

    return Scaffold(
      body: Stack(
        children: [
          GradientBackground(
            animated: true,
            child: SafeArea(
              child: Column(
                children: [
                  _buildHeader(themeColors),
                  if (_isLoading)
                    const Expanded(
                      child: Center(
                        child: CircularProgressIndicator(color: Colors.white),
                      ),
                    )
                  else if (_permissionDenied)
                    _buildPermissionDenied()
                  else
                    Expanded(
                      child: Column(
                        children: [
                          _buildSearchBar(themeColors),
                          _buildStats(themeColors),
                          Expanded(
                            child: _buildContactsList(themeColors),
                          ),
                        ],
                      ),
                    ),
                ],
              ),
            ),
          ),

          // Confetti overlay
          Align(
            alignment: Alignment.topCenter,
            child: ConfettiWidget(
              confettiController: _confettiController,
              blastDirectionality: BlastDirectionality.explosive,
              particleDrag: 0.05,
              emissionFrequency: 0.05,
              numberOfParticles: 50,
              gravity: 0.1,
              shouldLoop: false,
              colors: const [
                AppColors.islamicGreenPrimary,
                AppColors.premiumGold,
                AppColors.emotionalPurple,
                AppColors.joyfulOrange,
              ],
            ),
          ),
        ],
      ),
      floatingActionButton: _selectedContactIds.isNotEmpty
          ? FloatingActionButton.extended(
              onPressed: _isImporting ? null : _importSelected,
              backgroundColor: themeColors.primary,
              icon: _isImporting
                  ? const SizedBox(
                      width: 24,
                      height: 24,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: Colors.white,
                      ),
                    )
                  : const Icon(Icons.download_rounded),
              label: Text(
                _isImporting ? 'جاري الاستيراد...' : 'استيراد (${_selectedContactIds.length})',
                style: AppTypography.labelLarge.copyWith(color: Colors.white),
              ),
            )
          : null,
    );
  }

  Widget _buildHeader(ThemeColors themeColors) {
    return Padding(
      padding: const EdgeInsets.all(AppSpacing.md),
      child: Row(
        children: [
          IconButton(
            onPressed: () => context.pop(),
            icon: const Icon(Icons.arrow_forward_rounded, color: Colors.white),
          ),
          const SizedBox(width: AppSpacing.sm),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'استيراد جهات الاتصال',
                  style: AppTypography.headlineMedium.copyWith(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'اختر جهات الاتصال لإضافتهم كأقارب',
                  style: AppTypography.bodySmall.copyWith(
                    color: Colors.white.withOpacity(0.8),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    ).animate().fadeIn().slideY(begin: -0.1, end: 0);
  }

  Widget _buildSearchBar(ThemeColors themeColors) {
    return Padding(
      padding: const EdgeInsets.all(AppSpacing.md),
      child: TextField(
        controller: _searchController,
        onChanged: _filterContacts,
        style: AppTypography.bodyMedium.copyWith(color: Colors.white),
        decoration: InputDecoration(
          hintText: 'ابحث عن جهة اتصال...',
          hintStyle: AppTypography.bodyMedium.copyWith(
            color: Colors.white.withOpacity(0.5),
          ),
          prefixIcon: Icon(Icons.search_rounded, color: themeColors.primary),
          suffixIcon: _searchController.text.isNotEmpty
              ? IconButton(
                  icon: const Icon(Icons.clear_rounded, color: Colors.white60),
                  onPressed: () {
                    _searchController.clear();
                    _filterContacts('');
                  },
                )
              : null,
          filled: true,
          fillColor: Colors.white.withOpacity(0.1),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(AppSpacing.radiusLg),
            borderSide: BorderSide.none,
          ),
        ),
      ),
    ).animate().fadeIn().slideX(begin: -0.1, end: 0);
  }

  Widget _buildStats(ThemeColors themeColors) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: AppSpacing.md),
      child: Row(
        children: [
          Expanded(
            child: GlassCard(
              padding: const EdgeInsets.all(AppSpacing.md),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.contacts_rounded, color: themeColors.accent, size: 20),
                  const SizedBox(width: AppSpacing.sm),
                  Text(
                    '${_filteredContacts.length} جهة اتصال',
                    style: AppTypography.bodyMedium.copyWith(color: Colors.white),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(width: AppSpacing.sm),
          Expanded(
            child: GestureDetector(
              onTap: _selectAll,
              child: GlassCard(
                padding: const EdgeInsets.all(AppSpacing.md),
                gradient: _selectedContactIds.isNotEmpty ? themeColors.primaryGradient : null,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      _selectedContactIds.length == _filteredContacts.length
                          ? Icons.check_circle_rounded
                          : Icons.check_circle_outline_rounded,
                      color: Colors.white,
                      size: 20,
                    ),
                    const SizedBox(width: AppSpacing.sm),
                    Text(
                      'تحديد الكل',
                      style: AppTypography.bodyMedium.copyWith(color: Colors.white),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    ).animate().fadeIn().slideY(begin: 0.1, end: 0);
  }

  Widget _buildContactsList(ThemeColors themeColors) {
    if (_filteredContacts.isEmpty) {
      return Center(
        child: GlassCard(
          margin: const EdgeInsets.all(AppSpacing.xl),
          padding: const EdgeInsets.all(AppSpacing.xl),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text('🔍', style: TextStyle(fontSize: 64)),
              const SizedBox(height: AppSpacing.md),
              Text(
                'لا توجد جهات اتصال',
                style: AppTypography.titleLarge.copyWith(color: Colors.white),
              ),
              const SizedBox(height: AppSpacing.sm),
              Text(
                'جرب البحث بكلمة أخرى',
                style: AppTypography.bodyMedium.copyWith(
                  color: Colors.white.withOpacity(0.7),
                ),
              ),
            ],
          ),
        ),
      );
    }

    return ListView.builder(
      padding: const EdgeInsets.all(AppSpacing.md),
      itemCount: _filteredContacts.length,
      itemBuilder: (context, index) {
        final contact = _filteredContacts[index];
        final isSelected = _selectedContactIds.contains(contact.id);

        return GestureDetector(
          onTap: () => _toggleContact(contact.id),
          child: GlassCard(
            margin: const EdgeInsets.only(bottom: AppSpacing.sm),
            padding: const EdgeInsets.all(AppSpacing.md),
            gradient: isSelected ? themeColors.primaryGradient : null,
            child: Row(
              children: [
                // Avatar
                Container(
                  width: 50,
                  height: 50,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    gradient: isSelected
                        ? themeColors.goldenGradient
                        : LinearGradient(
                            colors: [
                              Colors.white.withOpacity(0.2),
                              Colors.white.withOpacity(0.1),
                            ],
                          ),
                  ),
                  child: Center(
                    child: Text(
                      contact.displayName.isNotEmpty
                          ? contact.displayName[0].toUpperCase()
                          : '؟',
                      style: AppTypography.headlineMedium.copyWith(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ),

                const SizedBox(width: AppSpacing.md),

                // Contact info
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        contact.displayName,
                        style: AppTypography.titleMedium.copyWith(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      if (contact.phones.isNotEmpty) ...[
                        const SizedBox(height: 4),
                        Text(
                          contact.phones.first.number,
                          style: AppTypography.bodySmall.copyWith(
                            color: Colors.white.withOpacity(0.7),
                          ),
                        ),
                      ],
                    ],
                  ),
                ),

                // Checkbox
                Icon(
                  isSelected ? Icons.check_circle_rounded : Icons.circle_outlined,
                  color: Colors.white,
                  size: 28,
                ),
              ],
            ),
          ),
        )
            .animate(delay: Duration(milliseconds: 50 * index))
            .fadeIn()
            .slideX(begin: -0.1, end: 0);
      },
    );
  }

  Widget _buildPermissionDenied() {
    return Expanded(
      child: Center(
        child: GlassCard(
          margin: const EdgeInsets.all(AppSpacing.xl),
          padding: const EdgeInsets.all(AppSpacing.xl),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.contacts_rounded, size: 64, color: Colors.white70),
              const SizedBox(height: AppSpacing.lg),
              Text(
                'إذن مطلوب',
                style: AppTypography.headlineMedium.copyWith(color: Colors.white),
              ),
              const SizedBox(height: AppSpacing.sm),
              Text(
                'نحتاج إلى إذن للوصول إلى جهات الاتصال لاستيرادها',
                style: AppTypography.bodyMedium.copyWith(
                  color: Colors.white.withOpacity(0.7),
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: AppSpacing.lg),
              GradientButton(
                text: 'طلب الإذن',
                icon: Icons.lock_open_rounded,
                onPressed: () {
                  setState(() {
                    _isLoading = true;
                    _permissionDenied = false;
                  });
                  _loadContacts();
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
